### ISSUE TITLE
TRANSLATE and LANG providers

### ISSUE THREAD

**Issue by bloodbare** [plone/pastanaga-angular#174]
Forcing this two providers with TRANSLATE and LANG keywords conflicts easily with main translation mechanisms that differ from pastanaga angular ones.

- I can not find on documentation how to instanciate Pastanaga angular with that providers.

- Would be great that has domain specific KEYS, like PA_TRANSLATE.

**Comment by ebrehault** [comment]
The doc is here: https://github.com/plone/pastanaga-angular#i18n

And yes we need better keys.

**Comment by ebrehault** [comment]
@bloodbare by the way, i have recently added the ability to provide several translation files that can override each other, so the main project can override the default translation from an underlying lib (that's detailed in the doc).
I will soon add a default translation file in pastanaga (my PR is not fully ready), providing translation for basic labels involved in pastanaga components (like `Close`, `OK`, `Filter`, etc.).
My plan is to put them in a `pastanaga` "key" (acting as a domain) :
```{
    pastanaga: {
        common: {
            actions: 'Actions',
            add: 'Add',
            back: 'Back',
            cancel: 'Cancel',
            ...
      }
   }
}```
It could be a general naming convention (each lib providing a translation file would use a given domain).
So when using a translation key in a template, it is clear which package it is coming from.

**Comment by mpellerin42** [comment]
Closing as it had no update on the last year.
