### ISSUE TITLE
Domain Names on Modules

### ISSUE THREAD

**Issue by bloodbare** [plone/pastanaga-angular#175]
Modules should be domain specific

- PaDropdownModule
- PaButtonsModule
....

**Comment by ebrehault** [comment]
On one hand, it is true it would avoid conflicts with similarly named modules coming from other packages and/or from the main app project.
On the other hand, why would we involve several "ButtonsModule" in the same project?

But ok, I guess it is cleaner.

**Comment by bloodbare** [comment]
I’m using Materials blocks and Pastanaga controls, works great but code is confusing on naming.

**Comment by mpellerin42** [comment]
Closing: this is done in version 2.x branch which will become master branch soon.
