### ISSUE TITLE
Login credentials not provided

### ISSUE THREAD

**Issue by ajayns** [plone/pastanaga-angular#37]
I know custom backends can be used with it, but the default backend seems to work perfectly with it right now and I'd like to explore it more. So can anyone provide me with the user:password for it?

@ebrehault @lellex @tisto

**Comment by ebrehault** [comment]
Give me your email, I'll send it to you.

**Comment by nileshgulia1** [comment]
Me too please: nileshgulia@gmail.com

**Comment by ajayns** [comment]
@ebrehault 
My email is: ajay.ns@outlook.com

Thanks!
