### ISSUE TITLE
Just checkout; yarn install; ng serve

### ISSUE THREAD

**Issue by bloodbare** [plone/pastanaga-angular#49]
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /Users/ramon/floss/pastanaga-angular/projects/pastanaga/src/lib/styles/_general.scss:15:143: Can't resolve './develop/pastanaga-angular/projects/pastanaga/src/assets/fonts/Poppins/Poppins-Regular.ttf' in '/Users/ramon/floss/pastanaga-angular/src'

**Comment by ebrehault** [comment]
Cannot reproduce (I did `npm install` but I guess yarn would make the same).

The following: `Can't resolve './develop/pastanaga-angular/projects/pastanaga/src/assets/fonts/Poppins/Poppins-Regular.ttf'` sounds like you are using pastanag-anular as a mrdeveloper dependency in a main project but you are trying to build the pastanaga demo project.
That's not possible (you can only build the main project).

**Comment by bloodbare** [comment]
It works, I cloned again the repo (I updated before from old version) and now works
```
git clone git@github.com:plone/pastanaga-angular
yarn install
ng serve
```

yarn -version: 1.10.1
node -v:  v10.12.0
