### ISSUE TITLE
Support external translation solutions

### ISSUE THREAD

**Issue by ebrehault** [plone/pastanaga-angular#584]
# Why?

Some apps already use a translation solution (like `ngx-translate` for example), and would prefer to keep on using it.
As Pastanaga uses its own translate pipe inside its components, we cannot just decide to use `ngx-translate`, because it would not apply to Pastanaga inner contents.

While it is very nice to have translation support in Pastanaga by default, it would be interesting to be able to plug an external translation solution to Pastanaga

# How?

The idea would be to optionally provide a translate function in the main app module.
This function would be used by the Pastanaga `TranslatePipe`.

**Comment by mpellerin42** [comment]
After investigations, it seems like the proposed solution cannot work without breaking the current translation system, as it would require Pastanaga `translatePipe` `transform` method to return `Observable<string>` as well as string. 

So we're working on a different approach:
- improve Pastanaga translation system to support flat json translation keys as well as the current hierarchical ones
- add a method in Pastanaga translateService allowing to dynamically add more translations

This way, we will be able to use both Pastanaga and another translation system (like `ngx-translate` for instance) side by side:
- we can have only one translation file by language which would be provided dynamically to both translation systems
- pastanaga will still take care of its own internal translations using its own translatePipe with external translation file
- the rest of the project can be translated using `ngx-translate`

**Comment by mpellerin42** [comment]
Done in version 2.52.0.
