### ISSUE TITLE
Upgrade to Angular 17

### ISSUE THREAD

**Issue by mpellerin42** [plone/pastanaga-angular#671]
Pastanaga-angular is currently using Angular v16. Angular 17 is out so we need to publish a new version of Pastanaga supporting Angular 17.

**Comment by ravjot07** [comment]
Hey, can you provide a description of what exactly you want?

**Comment by mpellerin42** [comment]
Hey @ravjot07, sorry I didn't provide a description because I planned to take care of this myself in the coming days (and I thought the title was quite self explanatory). I just added a short description though.
